### ISSUE TITLE
Typename should be a valid identifier: Scheduling Instructions

### ISSUE THREAD

**Issue by mnpenner** [ralusek/jsonschema-to-mobx-state-tree#1]
I'm trying to convert my JSON Schema to a MST model, but I'm getting this error.

I understand why, but AFAICT, spaces are legal in "title" of JSON Schema, just not in mobx-state-tree. Perhaps `jsonschema-to-mobx-state-tree` should sanitize the title instead of erroring out?

**Comment by ralusek** [comment]
Okay, will change. Camelcase, kebabcase, snakecase?

**Comment by mnpenner** [comment]
I would think UpperCamelCase would make most sense, since it's the name of
a type, no?

Thanks!

**Comment by ralusek** [comment]
So I changed it to replace title spaces with `-` by default, you can replace this by providing a `titleDelimiter` on import.

```
const jsonSchemaToTypes = require('jsonschema-to-mobx-state-tree')(types, {titleDelimiter: ''});
```

Providing `''`, for example, would just concatenate `'My Title'` to `'MyTitle'`. If you want something more custom, you can pass `formatTitle` property. To get UpperCamelCase using lodash, something like this:

```
const jsonSchemaToTypes = require('jsonschema-to-mobx-state-tree')(types, {
  formatTitle: (title, {titleDelimiter}) => _.startCase(title).replace(/\s+/g, '')
});
```

I also added babel precompile so hopefully that makes things easier. Let me know if there's anything else.

**Comment by mnpenner** [comment]
Sweet. Thank you!
